import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiFirebase,
  SiCplusplus,
  SiGit,
  SiGithub,
  SiLinux,
  SiMysql,
  SiFigma,
  SiGoogleanalytics,
  SiVirtualbox,
  SiArduino,
} from "react-icons/si";

import type { ReactNode } from "react";

export const techIconMap: Record<string, ReactNode> = {
  html: <SiHtml5 className="w-5 h-5 text-orange-500" />,
  css: <SiCss3 className="w-5 h-5 text-blue-500" />,
  javascript: <SiJavascript className="w-5 h-5 text-yellow-400" />,
  typescript: <SiTypescript className="w-5 h-5 text-blue-400" />,
  react: <SiReact className="w-5 h-5 text-cyan-400" />,
  "next.js": <SiNextdotjs className="w-5 h-5 text-white" />,
  "tailwind css": <SiTailwindcss className="w-5 h-5 text-sky-400" />,
  "node.js": <SiNodedotjs className="w-5 h-5 text-green-500" />,
  express: <SiExpress className="w-5 h-5 text-gray-300" />,
  firebase: <SiFirebase className="w-5 h-5 text-yellow-400" />,
  "rest apis": <SiGoogleanalytics className="w-5 h-5 text-orange-400" />,
  "c++": <SiCplusplus className="w-5 h-5 text-blue-500" />,
  git: <SiGit className="w-5 h-5 text-orange-500" />,
  github: <SiGithub className="w-5 h-5 text-white" />,
  sql: <SiMysql className="w-5 h-5 text-blue-400" />,
  figma: <SiFigma className="w-5 h-5 text-pink-500" />,
  linux: <SiLinux className="w-5 h-5 text-yellow-300" />,
  seo: <SiGoogleanalytics className="w-5 h-5 text-green-400" />,
  vms: <SiVirtualbox className="w-5 h-5 text-blue-500" />,
  automação: <SiArduino className="w-5 h-5 text-orange-500" />,
  iot: <SiArduino className="w-5 h-5 text-orange-400" />,
};
